### ISSUE TITLE
Bildelement wird nicht korrekt skaliert

### ISSUE THREAD

**Issue by TheSmartGerman** [Wolfgang-03/Open3E-HA#1]
Obwohl laut YAML Code eine fixe Größe vorgegeben ist, erscheint das Bild-Element bei mir verkleinert

```
type: picture-elements
image: /local/kreislauf.png
title: Viessmann Vitocal 250-A Kältekreislauf
style:
  width: 1280px
  height: 720px
```

![image](https://github.com/Wolfgang-03/Open3E-HA/assets/9676982/3f5944a3-3626-4818-bebd-de4eb95f6f36)

Am Handy wird es sehr klein, aber soweit noch erkennbar korrekt angezeigt...
Gibt es noch weitere Parameter zum die Größe zu Steuern? 

P.S.: ich habe mir noch einen "Arbeitszahl" template gebastelt...
