### ISSUE TITLE
Heizkreis 1 zeigt falsche Werte

### ISSUE THREAD

**Issue by TheSmartGerman** [Wolfgang-03/Open3E-HA#2]
Mein Heizkreis 1 zeigt recht "interessante" Werte:

![image](https://github.com/Wolfgang-03/Open3E-HA/assets/9676982/47b4a806-af23-4f1d-b461-29d6030abda8)

Ich werde mal suchen woher der Vorlaufwert kommt...

**Comment by Wolfgang-03** [comment]
Du musst nur auf den Text "Vorlauftemperatur Istwert" klicken und dann oben auf das Zahnrad. 
Ich habe die Entity-IDs so hinterlegt, dass der DID angezeigt wird von dem der Wert kommt. 
 
<img width="458" alt="image" src="https://github.com/Wolfgang-03/Open3E-HA/assets/80253488/1528fc6d-e2f9-4ff2-87d1-ee7601968ce4">

Kann sein, dass es diesen Temperaturfühler bei deiner Anlage nicht gibt. Bei mir ist ein "Divicon" (so heißt das Ding glaube ich) verbaut, welcher den Vorlauf auf 2 Heizkreise aufteilt. Für HK2 existiert dann noch ein Mischventil, über welchen die Temperatur für HK2 verringert werden kann. An HK2 (ist noch nicht in Betrieb) soll die geplante Fußbodenheizung angeschlossen werden, welche dann eine niedrigere Vorlauftemperatur benötigt. HK1 sind bei mir Heizkörper.

**Comment by TheSmartGerman** [comment]
Ok, verstanden. Ja ich habe auch einen Divicon, mit 2 Heizkreisen. Fußbodenheizung & Heizkörper, dann muss ich mal den korrekten Wert suchen.

**Comment by TheSmartGerman** [comment]
Also ich habe mir Heizung und die DIDs angesehen. In der Tat steht bei mir auf dem Divicon - Heizkreis 2 und Heizkreis 3. Somit habe ich keinen Heizkreis 1 sondern 2 und 3. Damit sollte das für "Heizkreis 3" verwendet werden:

```
# Vitocal 250 - Heizkreis 3
    - name: "Vitocal HK3 Vorlauftemperatur"
      state_topic: "open3e/680_288_MixerThreeCircuitFlowTemperatureSensor/Actual"
      unique_id: 680_288_MixerThreeCircuitFlowTemperatureSensor
      object_id: 288_mixerthreecircuitflowtemperaturesensor
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N 1234567890123456"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      unit_of_measurement: "°C"

    - name: "Vitocal HK3 Position Mischventil"
      state_topic: "open3e/680_477_MixerThreeCircuitThreeWayValvePositionPercent"
      unique_id: 680_477_MixerThreeCircuitThreeWayValvePositionPercent
      object_id: 477_mixerthreecircuitthreewayvalvepositionpercent
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N 1234567890123456"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      icon: mdi:valve
      value_template: >
        {{ float(value) / 100 }}

    - name: "Vitocal HK3 Vorlauftemperatur Sollwert"
      state_topic: "open3e/680_989_MixerThreeCircuitFlowTemperatureTargetSetpoint"
      unique_id: 680_989_MixerThreeCircuitFlowTemperatureTargetSetpoint
      object_id: 989_mixerthreecircuitflowtemperaturetargetsetpoint
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N 1234567890123456"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      unit_of_measurement: "°C"

    - name: "Vitocal HK3 Betriebsprogramm"
      state_topic: "open3e/680_1417_MixerThreeCircuitOperationState/State"
      unique_id: 680_1416_MixerThreeCircuitOperationState
      object_id: 1416_mixerthreecircuitoperationstate
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N 1234567890123456"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      icon: mdi:home-variant
      value_template: >
        {% set ostate = int(value) %}
        {% if ostate==0 %}
          {{ "Abschaltbetrieb" }}
        {% elif ostate==1 %}
          {{ "Reduziert" }}
        {% elif ostate==2 %}
          {{ "Normal" }}
        {% elif ostate==3 %}
          {{ "Komfort" }}
        {% elif ostate==4 %}
          {{ "Festwert" }}
        {% elif ostate==5 %}
          {{ "Frostschutz" }}
        {% elif ostate==6 %}
          {{ "Energiesparen Reduziert" }}
        {% elif ostate==7 %}
          {{ "Energiesparen Normal" }}
        {% elif ostate==8 %}
          {{ "Energiesparen Komfort" }}
        {% else %}
          {{ value }}
        {% endif %}

    - name: "Vitocal HK3 Solltemperatur"
      state_topic: "open3e/680_1645_MixerThreeCircuitCurrentTemperatureSetpoint"
      unique_id: 680_1644_MixerThreeCircuitCurrentTemperatureSetpoint
      object_id: 1644_mixerthreecircuitcurrenttemperaturesetpoint
      device:
        name: "Open3e_Vitocal250A"
        identifiers: "S/N 1234567890123456"
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      device_class: temperature
      state_class: measurement
      icon: mdi:thermometer
      unit_of_measurement: "°C"
```

Der Identifier könnte durch 377 abgefragt werden, wäre das sinnvoll? bzw. kann dies im Yaml dann auch eingefügt werden?
